spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalFilters:
        - name: CircuitBreaker
          args:
            name: gateway-server
            fallbackUri: forward:/fallback
  #zipkin
  management:
    tracing:
      enabled: true
    zipkin:
      tracing:
        enabled: true
        endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: true


resilience4j:
  circuitbreaker:
    instances:
      gateway-server:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000 # milliseconds
