spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalFilters:
        - name: circuit breaker
          args:
            name: gateway-server
            fallbackUri: forward:/fallback
  #zipkin
management:
  endpoints:
    web:
      exposure:
        include: mappings,health
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      enabled: true
      endpoint: http://localhost:9411/api/v2/spans


eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: true


resilience4j:
  circuit breaker:
    instances:
      gateway-server:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000 # milliseconds
