version: "3.8"
services:
  eureka-server:
    image: iamleslie/eureka-server:latest
    container_name: eureka-server
    depends_on:
      - zipkin
    ports:
      - "8761:8761"

  gateway-server:
    image: iamleslie/gateway-server:latest
    container_name: gateway-server
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker


  product-service:
    image: iamleslie/product-service:latest
    container_name: product-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - kafka
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=docker


  order-service:
    image: iamleslie/order-service:latest
    container_name: order-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - product-service
      - kafka
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=docker
#      Redis needs this env variable to run order service
      - JAVA_TOOL_OPTIONS=--add-opens=java.base/java.nio.charset=ALL-UNNAMED

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411


  kafka:
    image: apache/kafka:latest
    container_name: broker
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://broker:9092,CONTROLLER://broker:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    ports:
      - "9092:9092"
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379

        #  elasticsearch:
#    image: elasticsearch:8.17.1
#    container_name: elasticsearch
##    volumes:
##      - esdata1:/usr/share/elasticsearch/data
#    environment:
#      - ELASTIC_PASSWORD=password
#    ports:
#      - 9300:9300
#      - 9200:9200
#  kibana:
#    image: kibana:8.17.1
#    container_name: kibana
#    environment:
#      ELASTICSEARCH_URL: "http://elasticsearch:9300"
#      ELASTIC_PASSWORD: "password"
#    ports:
#      - 5601:5601
#
#  logstash:
#    image: logstash:8.17.1
#    container_name: logstash
#    command: logstash -f /etc/logstash/conf.d/logstash.conf
#    volumes:
#      - ./logstash.conf:/etc/logstash/conf.d/logstash.conf
#
#    ports:
#      - "5001:5001"   # Map port 5001 for TCP input (matching your logstash.conf)
#      - "9600:9600"


