version: "3.8"
services:
  eureka-server:
    image: iamleslie/eureka-server:latest
    container_name: eureka-server
    depends_on:
      - zipkin
    ports:
      - "8761:8761"

  gateway-server:
    image: iamleslie/gateway-server:latest
    container_name: gateway-server
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker


  product-service:
    image: iamleslie/product-service:latest
    container_name: product-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker


  order-service:
    image: iamleslie/order-service:latest
    container_name: order-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - product-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411

#  elasticsearch:
#    image: elasticsearch:8.17.1
#    container_name: elasticsearch
##    volumes:
##      - esdata1:/usr/share/elasticsearch/data
#    environment:
#      - ELASTIC_PASSWORD=password
#    ports:
#      - 9300:9300
#      - 9200:9200
#  kibana:
#    image: kibana:8.17.1
#    container_name: kibana
#    environment:
#      ELASTICSEARCH_URL: "http://elasticsearch:9300"
#      ELASTIC_PASSWORD: "password"
#    ports:
#      - 5601:5601
#
#  logstash:
#    image: logstash:8.17.1
#    container_name: logstash
#    command: logstash -f /etc/logstash/conf.d/logstash.conf
#    volumes:
#      - ./logstash.conf:/etc/logstash/conf.d/logstash.conf
#
#    ports:
#      - "5001:5001"   # Map port 5001 for TCP input (matching your logstash.conf)
#      - "9600:9600"


