server:
  port: 8082

spring:
  application:
    name: order-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL:jdbc:postgresql://db:5432/}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update  # Automatically create the schema (use 'create' or 'update')
    show-sql: true      # Show SQL queries in the console
  cloud:
    function:
      definition: productConsumer;productEvent
    stream:
      bindings:
        productConsumer-in-0: # binding name (kafka)
          destination: productConsumer-topic  # Topic (Data is kept here)
          group: productConsumer-group
          content-type: application/json
        productEvent-in-0:
          destination: productSupplier-topic
          content-type: application/json
          group: productEvent-group
        productEvent-out-0:
          content-type: application/json
          destination: productConsumer-topic
      kafka:
        binder:
          brokers: ${BROKER_ADDRESS:broker:9092}
    

  data:
    redis:
      port: 6379
      host: ${REDIS:redis}
#    zipkin and health monitoring
management:
  endpoints:
    web:
      exposure:
        include: mappings,health,metrics
  tracing:
    enabled: true
    sampling:
      probability: 0.3
  zipkin:
    tracing:
      enabled: true
      endpoint: http://zipkin:9411/api/v2/spans



# Eureka
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://Eureka-Server:8761/eureka/}
    enabled: true


#Client side resilience pattern
resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-size: 5
        permitted-number-of-calls-in-half-open-state:  3
        wait-duration-in-open-state:
          seconds: 5s
        failure-rate-threshold: 20
    instances:
      order-service:
        baseConfig: default
  retry:
    instances:
      retryOrderService:
        max-attempts: 5
        wait-duration: 1000
        retry-exceptions:
          - java.util.concurrent.TimeoutException
  ratelimiter:
    configs:
      default:
        timeoutDuration: 1000ms
        limitRefreshPeriod: 1000ms
        limitForPeriod: 2
    instances:
      order-service:
        baseConfig: default