apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: config-server
  name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: config-server
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: config-server
    spec:
      containers:
        - image: iamleslie/config-server:latest
          name: config-server
          #          livenessProbe:
          #            httpGet:
          #              port: 8081
          #            initialDelaySeconds: 60
          #          readinessProbe:
          #            exec:
          #              command:
          #                - ls
          #                - /var/ready
          ports:
            - containerPort: 8045
              protocol: TCP
      restartPolicy: Always
