apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: order-service
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: order-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: order-service
    spec:
      containers:
        - env:
            - name: JAVA_TOOL_OPTIONS
              value: --add-opens=java.base/java.nio.charset=ALL-UNNAMED
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: EUREKA_SERVER_URL
              value: http://eureka-server.default.svc.cluster.local:8761/eureka/
          image: iamleslie/order-service:latest
          imagePullPolicy: Always
          name: order-service
          ports:
            - containerPort: 8082
              protocol: TCP
      restartPolicy: Always
