apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: product-service
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: product-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: product-service
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: EUREKA_SERVER_URL
              value: http://eureka-server.default.svc.cluster.local:8761/eureka/
          image: iamleslie/product-service:latest
#          livenessProbe:
#            httpGet:
#              port: 8081
#            initialDelaySeconds: 60
#          readinessProbe:
#            exec:
#              command:
#              - ls
#              - /var/ready
          imagePullPolicy: Always
          name: product-service
          ports:
            - containerPort: 8081
              protocol: TCP
      restartPolicy: Always
