spring:
  application:
    name: configserver
  profiles:
    active: native
  cloud:
    config:
      discovery:
        enabled: true
        service-id:
      server:
        native:
          search-locations: classpath:/config
server:
  port: 8045

