server:
  port: 8082

spring:
  application:
    name: order-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:orderdb
    username: sa
    password: password
    hikari:
      pool-name: H2Pool
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update  # Automatically create the schema (use 'create' or 'update')
    show-sql: true      # Show SQL queries in the console
    database-platform: org.hibernate.dialect.H2Dialect
#    zipkin and health monitoring
management:
  endpoints:
    web:
      exposure:
        include: mappings,health
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      enabled: true
      endpoint: http://zipkin:9411/api/v2/spans

#  cloud:
#    stream:
#      bindings:
#        output:
#          destination: Supplier
#          content-type: application/json
#          binder: kafka
#      kafka:
#        binder:
#          brokers: localhost:9092
#          zkNodes: localhost:2181

# Eureka
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://Eureka-Server:8761/eureka/
    enabled: true


#Client side resilience pattern
resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-size: 5
        permitted-number-of-calls-in-half-open-state:  3
        wait-duration-in-open-state:
          seconds: 5s
        failure-rate-threshold: 20
    instances:
      order-service:
        baseConfig: default
  retry:
    instances:
      retryOrderService:
        max-attempts: 5
        wait-duration: 1000
        retry-exceptions:
          - java.util.concurrent.TimeoutException
  ratelimiter:
    configs:
      default:
        timeoutDuration: 1000ms
        limitRefreshPeriod: 5000ms
        limitForPeriod: 5
    instances:
      order-service:
        baseConfig: default

product-service:
  url: http://product:8081
