spring:
  application:
    name: product-service
  profiles:
    active: default
  config:
    import: configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8045} # Didnt add optional for failing fast


