server:
  port: 8081

spring:
  application:
    name: product-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:productdb
    username: sa
    password: password
    hikari:
      pool-name: H2Pool
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update  # Automatically create the schema (use 'create' or 'update')
    show-sql: true      # Show SQL queries in the console
    database-platform: org.hibernate.dialect.H2Dialect
management:
  endpoints:
    web:
      exposure:
        include: mappings,health

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: true

#resilience4j:
#  circuitbreaker:
#    instances:
#      myCircuitBreaker:
#        slidingWindowSize: 100
#        slidingWindowType: COUNT_BASED
#        failureRateThreshold: 50
#        waitDurationInOpenState: 10s
#        registerHealthIndicator: true
#  retry:
#    instances:
#      myRetry:
#        maxAttempts: 3
#        waitDuration: 1s
#  ratelimiter:
#    instances:
#      myRateLimiter:
#        limitForPeriod: 10
#        timeoutDuration: 5s
#        limitRefreshPeriod: 1s
#  bulkhead:
#    instances:
#      myBulkhead:
#        maxConcurrentCalls: 25
#        maxWaitDuration: 1s
#  thread-pool-bulkhead:
#    instances:
#      myThreadPoolBulkhead:
#        coreThreadPoolSize: 10
#        maxThreadPoolSize: 20
#        queueCapacity: 50
#  timelimiter:
#    instances:
#      myTimeLimiter:
#        timeoutDuration: 2s
#        cancelRunningFuture: true
