spring:
  application:
    name: product-service
  profiles:
    active: default
  config:
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8045} # Added Optional for testing purpose
                                                                                  # if you want it to fail fast remove optional but tests will fail


