apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: product-h2-database
spec:
  resources:
    requests:
      storage: 200Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: "standard"